### ISSUE TITLE
Remove Money from MoneyFormatter

### ISSUE THREAD

**Issue by sagikazarmark** [mathiasverraes/money#145]
@frederikbosch WDYT? Is there any added value of calling it MoneyFormatter? Can we think of any possible future formatters, which are not for money?

**Comment by frederikbosch** [comment]
@sagikazarmark Agree, the prefix Money is not required. Actually, I never know when to suffix or prefix a class with its functionality. I never read upon a good standard for it. My current methodology is to think of the users of the class. What would he/she want the class name to be when it is being used?

So with the `MoneyFormatter`, does the class name describe its actual meaning? I think it does. When the class/interface name would be only `Formatter`, it could be confusing in code of the user when there are multiple Formatter classes in the user's code. Then he/she would be required to do `use Formatter as MoneyFormatter`.

Maybe I am exaggerating, but why rename the `Money\Money` to `Money\Value`? Because it would give the same confusion in user's code, renaming the object to `Money\Money` or `Money\MoneyValue`.

But if there are valid reasons to do it differently, please correct me. I am merely applying my own standards here.

**Comment by frederikbosch** [comment]
@sagikazarmark What do we do when there is `PreciseMoney` in `3.1.0`. Can a `PreciseMoney` object be formatted with the same `MoneyFormatter` as we are using now? Or do we need a `PreciseMoneyFormatter` interface?

**Comment by sagikazarmark** [comment]
Okay, rethinking this: MoneyFormatter makes sense. In theory (even if doesn't make sense) CurrencyFormatter would be a viable option.

I haven't thought about a PreciseMoney implementation yet, so that would require a custom formatter interface.
